In [4]:
import numpy as np

list = [1,2,3,4]

array = np.array(list)

print(array)

[1 2 3 4]


In [6]:
list = [[1,2,3], [4,5,6]]

array = np.array(list)

print(array)

[[1 2 3]
 [4 5 6]]


In [9]:
array = np.arange(1, 17)
array = array.reshape(4,4)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [10]:
tuple = (1,2,3,4)
array = np.array(tuple)
print(array)

[1 2 3 4]


In [11]:
tuple = (1,2,3,4)
array = np.array(tuple)

print(array[1] + array[2])

5


In [14]:
array = np.arange(1,50)
array = array.reshape(7, 7)
print(array[3][3])

25


In [15]:
array = np.arange(1,50)
array = array.reshape(7, 7)
array[0] = 0
print(array)

[[ 0  0  0  0  0  0  0]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]


In [17]:
array = np.arange(1,17)
array = array.reshape(4, 4)
print(array[3])

[13 14 15 16]


In [18]:
array = np.arange(1,17)
array = array.reshape(4, 4)
print(array[2:4])

[[ 9 10 11 12]
 [13 14 15 16]]


In [28]:
print(array[: , 2:])

[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [31]:
print(array[1:3 , 1:3])

[[ 6  7]
 [10 11]]


In [40]:
print(array[1:3 , 1::2])

[[ 6  8]
 [10 12]]


In [41]:
print(array[:2 , ::3])

[[1 4]
 [5 8]]


In [44]:
array = [[0,0,0],
        [1,2,3],
        [4,5,6]]
add_values = np.array([10, 20, 30])
result = array + add_values[:, np.newaxis]
print(result)

[[10 10 10]
 [21 22 23]
 [34 35 36]]


In [45]:
arr_1 = [[1, 2], [3, 4]]
arr_2 = [[5, 6], [7, 8]]
result = np.dot(arr_1, arr_2)
print(result)

[[19 22]
 [43 50]]
